project_root: "C:/HRI_World_Model"
data_root: "E:/HRI_World_Model_Data"
raw_rosbags: "E:/HRI_World_Model_Data/00_raw_rosbags"
metadata: "E:/HRI_World_Model_Data/01_metadata"
synchronized_trials: "E:/HRI_World_Model_Data/02_synchronized_trials"
processed_skeleton: "E:/HRI_World_Model_Data/03_processed_skeleton"
rgb_keyframes: "E:/HRI_World_Model_Data/04_rgb_keyframes"
datasets: "E:/HRI_World_Model_Data/07_datasets"
models: "E:/HRI_World_Model_Data/08_models"
checkpoints: "E:/HRI_World_Model_Data/09_checkpoints"
results: "E:/HRI_World_Model_Data/10_results"
