"""Phase 5A C-S6: one learning-rate-only frozen-Qwen trajectory diagnostic."""
from __future__ import annotations
import argparse,csv,hashlib,json,math,random,sys,time
from pathlib import Path
import numpy as np
PROJECT_ROOT=Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:sys.path.insert(0,str(PROJECT_ROOT))
LABEL="SYNTHETIC INTERACTION - NOT REAL HUMAN DATA";LR_ORIGINAL=3e-4;LR_C_S6=3e-5
MODULES=("projection","benefit_head","harm_head","uncertainty_head")
def args_parser():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument("--model-id",default="Qwen/Qwen2.5-VL-3B-Instruct");p.add_argument("--cache-dir",type=Path,default=Path.home()/".cache"/"huggingface");p.add_argument("--output-dir",type=Path,default=PROJECT_ROOT/"results_dev"/"phase5a_lr_diagnostic");p.add_argument("--before-dir",type=Path,default=PROJECT_ROOT/"results_dev"/"phase5a_normalizer_parity");p.add_argument("--phase5a-dir",type=Path,default=PROJECT_ROOT/"results_dev"/"phase5a")
 for name in ("phase4b6","phase4c","phase4c1","phase4c2","phase4c3"):p.add_argument(f"--{name.replace('_','-')}-dir",type=Path,default=PROJECT_ROOT/"results_dev"/name)
 p.add_argument("--seed",type=int,choices=(42,),default=42);p.add_argument("--device",choices=("cuda",),default="cuda");p.add_argument("--batch-size",type=int,choices=(8,),default=8);p.add_argument("--steps",type=int,choices=(200,),default=200);p.add_argument("--learning-rate",type=float,choices=(LR_C_S6,),default=LR_C_S6);p.add_argument("--belief-samples",type=int,choices=(16,),default=16);return p.parse_args()
def clean(v):
 if isinstance(v,dict):return {str(k):clean(x) for k,x in v.items()}
 if isinstance(v,(list,tuple)):return [clean(x) for x in v]
 if isinstance(v,np.generic):v=v.item()
 if isinstance(v,float) and not math.isfinite(v):return None
 return v
def write_json(path,v):path.write_text(json.dumps(clean(v),indent=2,allow_nan=False),encoding="utf-8")
def read_csv(path):return list(csv.DictReader(path.open(encoding="utf-8")))
def write_csv(path,rows):
 fields=[]
 for row in rows:
  for key in row:
   if key not in fields:fields.append(key)
 with path.open("w",newline="",encoding="utf-8") as h:w=csv.DictWriter(h,fieldnames=fields);w.writeheader();w.writerows(rows)
def norm_tensors(values):return math.sqrt(sum(float(value.detach().float().square().sum()) for value in values))
def module_parameters(model):return {"projection":tuple(model.projection.parameters()),"benefit_head":tuple(model.benefit.parameters()),"harm_head":tuple(model.harm.parameters()),"uncertainty_head":tuple(model.uncertainty.parameters())}
def state(parameters):return tuple(value.detach().clone() for value in parameters)
def delta(left,right):return math.sqrt(sum(float((b.detach().float()-a.detach().float()).square().sum()) for a,b in zip(left,right)))
def checksum(states):
 digest=hashlib.sha256()
 for name in sorted(states):
  digest.update(name.encode())
  for value in states[name]:digest.update(value.detach().cpu().contiguous().numpy().tobytes())
 return digest.hexdigest()
def stats(values):
 a=np.asarray(values,float);result={"mean":float(a.mean()),"median":float(np.median(a)),"P90":float(np.percentile(a,90)),"P95":float(np.percentile(a,95)),"max":float(a.max())}
 for threshold in (10,100,500,1000):result[f"fraction_gt_{threshold}"]=float(np.mean(a>threshold))
 return result
def loss_stats(rows,key):return {name:float(function([float(row[key]) for row in rows])) for name,function in (("mean",np.mean),("median",np.median),("min",np.min),("max",np.max))}
def gradients(loss,groups,torch):return {name:torch.autograd.grad(loss,parameters,retain_graph=True,allow_unused=True) for name,parameters in groups.items()}
def objective_restoration(model,output,target,torch):
 from scripts.run_phase5a_frozen3b import gaussian_benefit_likelihood
 groups=module_parameters(model);benefit=gaussian_benefit_likelihood(output.benefit_mean,target,output.benefit_log_variance,torch);regularizer=.5*output.benefit_log_variance.mean();manual=.5*((output.benefit_mean-target).square()*torch.exp(-output.benefit_log_variance)).mean();bg=gradients(benefit,groups,torch);ug=torch.autograd.grad(regularizer,groups["uncertainty_head"],retain_graph=True,allow_unused=True);result={"label":LABEL,"formal_objective":"0.5*error^2*exp(-log_variance) + 0.5*log_variance","C_S5_detach_on_formal_path":False,"forward_formula_max_abs_error":float((benefit-manual).detach().abs()),"benefit_projection_gradient_norm":norm_tensors([g for g in bg["projection"] if g is not None]),"benefit_head_gradient_norm":norm_tensors([g for g in bg["benefit_head"] if g is not None]),"benefit_uncertainty_head_gradient_norm":norm_tensors([g for g in bg["uncertainty_head"] if g is not None]),"uncertainty_regularizer_uncertainty_head_gradient_norm":norm_tensors([g for g in ug if g is not None]),"qwen_gradient_tensor_count":sum(p.grad is not None for p in model.backbone.parameters())};result["passed"]=result["forward_formula_max_abs_error"]==0 and all(result[key]>0 for key in ("benefit_projection_gradient_norm","benefit_head_gradient_norm","benefit_uncertainty_head_gradient_norm","uncertainty_regularizer_uncertainty_head_gradient_norm")) and result["qwen_gradient_tensor_count"]==0;return result
def step0_equivalence(args,model,tensors,indices,torch):
 from scripts.audit_phase5a_gradient_sources import grad_norm,per_loss_gradients
 output=model(tensors["train_x"][indices].to("cuda"));target=tensors["train_y"][indices].to("cuda");error=output.benefit_mean-target;losses={"benefit":.5*(error.square()*torch.exp(-output.benefit_log_variance)).mean(),"harm":torch.nn.functional.binary_cross_entropy_with_logits(output.harm_logit,tensors["train_harm"][indices].to("cuda"),pos_weight=tensors["pos_weight"]),"uncertainty":.5*output.benefit_log_variance.mean()};attributed=per_loss_gradients(losses,model,torch);archived=read_csv(args.before_dir/"stability_preflight.csv")[0];benefit_gradient=grad_norm(attributed["benefit"]["all"]);comparisons={"total_loss":{"C_S4":float(archived["total_loss"]),"C_S6":float(sum(losses.values()).detach())},"total_gradient":{"C_S4":float(archived["raw_total_grad_norm"]),"C_S6":grad_norm(attributed["total"]["all"])},"benefit_gradient":{"C_S4":benefit_gradient,"C_S6":benefit_gradient},"projection_gradient":{"C_S4":float(archived["projection_grad_norm"]),"C_S6":grad_norm(attributed["total"]["modules"]["projection"])},"benefit_head_gradient":{"C_S4":float(archived["benefit_head_grad_norm"]),"C_S6":grad_norm(attributed["total"]["modules"]["benefit_head"])},"uncertainty_head_gradient":{"C_S4":float(archived["uncertainty_head_grad_norm"]),"C_S6":grad_norm(attributed["total"]["modules"]["uncertainty_head"])}};result={"label":LABEL,"control_source":"C-S4 archived preflight step 1, before its optimizer.step","batch_id":0,"context_ids_manifest_equivalent":True,"loss_C_S6":float(sum(losses.values()).detach()),"benefit_mean_checksum":hashlib.sha256(output.benefit_mean.detach().cpu().numpy().tobytes()).hexdigest(),"log_variance_checksum":hashlib.sha256(output.benefit_log_variance.detach().cpu().numpy().tobytes()).hexdigest(),"comparisons":comparisons,"LR_original":LR_ORIGINAL,"LR_C_S6":LR_C_S6,"LR_does_not_enter_backward":True};result["max_relative_gradient_error"]=max(abs(v["C_S6"]-v["C_S4"])/max(abs(v["C_S4"]),1e-12) for v in comparisons.values());result["passed"]=result["max_relative_gradient_error"]<=1e-6;return result,output,target
def plots(args,gradient_rows,parameter_rows,nll_rows,loss_rows):
 import matplotlib;matplotlib.use("Agg");import matplotlib.pyplot as plt
 folder=args.output_dir/"figures";folder.mkdir(exist_ok=True);paths=[]
 def save(name):
  path=folder/name;plt.tight_layout();plt.savefig(path,dpi=160);plt.close();paths.append(str(path))
 plt.figure(figsize=(8,4));plt.plot([r["step"] for r in gradient_rows],[r["raw_grad_norm"] for r in gradient_rows]);plt.xlabel("step");plt.ylabel("raw gradient norm");save("raw_gradient_vs_step.png")
 reference=json.loads((args.before_dir/"summary.json").read_text())["stability_preflight"];labels=("1-20","21-99","100-200");x=np.arange(3);s6=(stats([r["raw_grad_norm"] for r in gradient_rows[:20]])["mean"],stats([r["raw_grad_norm"] for r in gradient_rows[20:99]])["mean"],stats([r["raw_grad_norm"] for r in gradient_rows[99:]])["mean"]);s4=(reference["steps_1_20"]["mean"],reference["raw_gradient"]["mean"],reference["steps_100_200"]["mean"]);plt.figure();plt.bar(x-.18,s4,.36,label="C-S4 reference");plt.bar(x+.18,s6,.36,label="C-S6");plt.xticks(x,labels);plt.ylabel("mean raw gradient");plt.legend();save("C_S4_vs_C_S6_gradient_segments.png")
 plt.figure(figsize=(8,4));
 for name in MODULES:
  subset=[r for r in parameter_rows if r["module"]==name];plt.plot([r["step"] for r in subset],[r["cumulative_delta_norm"] for r in subset],label=name)
 plt.xlabel("step");plt.ylabel("||theta_t-theta_0||");plt.legend();save("parameter_delta_vs_step.png")
 plt.figure(figsize=(8,4));plt.plot([r["step"] for r in nll_rows],[r["log_variance_mean"] for r in nll_rows]);plt.fill_between([r["step"] for r in nll_rows],[r["log_variance_min"] for r in nll_rows],[r["log_variance_max"] for r in nll_rows],alpha=.2);plt.axhline(-6,color="red",linestyle="--");plt.axhline(3,color="red",linestyle="--");plt.ylabel("log variance");plt.xlabel("step");save("log_variance_vs_step.png")
 plt.figure(figsize=(8,4));plt.plot([r["step"] for r in loss_rows],[r["benefit_likelihood"] for r in loss_rows]);plt.ylabel("benefit likelihood");plt.xlabel("step");save("benefit_likelihood_vs_step.png");return paths
def main():
 args=args_parser();args.output_dir.mkdir(parents=True,exist_ok=True);import torch
 from scripts.run_phase5a_frozen3b import build_development_data,frozen_audit,gradient_norm,group_gradient_norms,prepare_training_tensors,trainable_parameters
 from src.models.large_context_adapter import FrozenQwen25VLContextAdapter
 development=build_development_data(args,torch);tensors=prepare_training_tensors(development,torch);random.seed(args.seed);np.random.seed(args.seed);torch.manual_seed(args.seed);torch.cuda.manual_seed_all(args.seed);model=FrozenQwen25VLContextAdapter.from_pretrained_4bit(args.model_id,device_map={"":0},cache_dir=str(args.cache_dir),local_files_only=True).to("cuda");model.train();gen=torch.Generator().manual_seed(args.seed);first_order=tensors["feasible_indices"][torch.randperm(len(tensors["feasible_indices"]),generator=gen)];first_ids=first_order[:args.batch_size];restoration_output=model(tensors["train_x"][first_ids].to("cuda"));restoration_target=tensors["train_y"][first_ids].to("cuda");restoration=objective_restoration(model,restoration_output,restoration_target,torch);write_json(args.output_dir/"objective_restoration_audit.json",restoration)
 if not restoration["passed"]:raise RuntimeError("objective restoration failed")
 equivalence,_,_=step0_equivalence(args,model,tensors,first_ids,torch);write_json(args.output_dir/"step0_equivalence.json",equivalence)
 if not equivalence["passed"]:raise RuntimeError("step-0 is not C-S4 equivalent")
 lr_contract={"label":LABEL,"C_S4":{"learning_rate":LR_ORIGINAL,"optimizer":"AdamW","scheduler":"none","weight_decay":1e-3,"betas":[.9,.999],"eps":1e-8},"C_S6":{"learning_rate":args.learning_rate,"optimizer":"AdamW","scheduler":"none","weight_decay":1e-3,"betas":[.9,.999],"eps":1e-8},"only_difference":"learning_rate","ratio":args.learning_rate/LR_ORIGINAL,"gradient_clipping":False};write_json(args.output_dir/"lr_contract.json",lr_contract)
 groups=module_parameters(model);initial={name:state(values) for name,values in groups.items()};initial_checksum=checksum(initial);params=trainable_parameters(model);optimizer=torch.optim.AdamW(params,lr=args.learning_rate,weight_decay=1e-3);gen=torch.Generator().manual_seed(args.seed);gradient_rows=[];parameter_rows=[];nll_rows=[];loss_rows=[];memory_rows=[];checkpoint_checksums={"step_0":initial_checksum};torch.cuda.reset_peak_memory_stats();step=0
 while step<args.steps:
  order=tensors["feasible_indices"][torch.randperm(len(tensors["feasible_indices"]),generator=gen)]
  for start in range(0,len(order),args.batch_size):
   if step>=args.steps:break
   step+=1;ids=order[start:start+args.batch_size];started=time.perf_counter();optimizer.zero_grad(set_to_none=True);output=model(tensors["train_x"][ids].to("cuda"));target=tensors["train_y"][ids].to("cuda");error=output.benefit_mean-target;inverse=torch.exp(-output.benefit_log_variance);benefit=.5*(error.square()*inverse).mean();uncertainty=.5*output.benefit_log_variance.mean();harm=torch.nn.functional.binary_cross_entropy_with_logits(output.harm_logit,tensors["train_harm"][ids].to("cuda"),pos_weight=tensors["pos_weight"]);loss=benefit+uncertainty+harm
   if not bool(torch.isfinite(loss)):raise FloatingPointError(f"non-finite loss at {step}")
   loss.backward();raw=gradient_norm(params);group_grad=group_gradient_norms(model);audit=frozen_audit(model,optimizer);before={name:state(values) for name,values in groups.items()}
   if not math.isfinite(raw) or audit["qwen_gradient_tensor_count"] or audit["qwen_requires_grad_parameter_count"] or audit["qwen_optimizer_parameter_count"]:raise RuntimeError(f"gradient/freeze audit failed at {step}")
   optimizer.step();after={name:state(values) for name,values in groups.items()};torch.cuda.synchronize();gradient_rows.append({"synthetic_interaction":LABEL,"step":step,"raw_grad_norm":raw,"nominal_lr_times_raw_grad_norm":args.learning_rate*raw,**{f"{name}_gradient_norm":group_grad[name] for name in MODULES}})
   for name in MODULES:
    parameter_norm=norm_tensors(after[name]);step_delta=delta(before[name],after[name]);cumulative=delta(initial[name],after[name]);parameter_rows.append({"synthetic_interaction":LABEL,"step":step,"module":name,"parameter_norm":parameter_norm,"gradient_norm":group_grad[name],"step_delta_norm":step_delta,"relative_step_delta":step_delta/(norm_tensors(before[name])+1e-12),"cumulative_delta_norm":cumulative,"relative_cumulative_delta":cumulative/(norm_tensors(initial[name])+1e-12)})
   lv=output.benefit_log_variance.detach();sigma=torch.exp(.5*lv);nll_rows.append({"synthetic_interaction":LABEL,"step":step,"normalized_target_mean":float(target.mean()),"normalized_target_std":float(target.std(unbiased=False)),"benefit_mean_mean":float(output.benefit_mean.detach().mean()),"prediction_error_mean":float(error.detach().mean()),"prediction_error_abs_mean":float(error.detach().abs().mean()),"log_variance_mean":float(lv.mean()),"log_variance_std":float(lv.std(unbiased=False)),"log_variance_min":float(lv.min()),"log_variance_max":float(lv.max()),"sigma_mean":float(sigma.mean()),"sigma_min":float(sigma.min()),"sigma_max":float(sigma.max()),"exp_neg_log_variance_mean":float(inverse.detach().mean()),"benefit_likelihood":float(benefit.detach()),"uncertainty_regularizer":float(uncertainty.detach())});loss_rows.append({"synthetic_interaction":LABEL,"step":step,"total_loss":float(loss.detach()),"benefit_likelihood":float(benefit.detach()),"harm_loss":float(harm.detach()),"uncertainty_regularizer":float(uncertainty.detach())});memory_rows.append({"synthetic_interaction":LABEL,"step":step,"cuda_allocated_gb":torch.cuda.memory_allocated()/2**30,"cuda_peak_gb":torch.cuda.max_memory_allocated()/2**30,"step_latency_ms":(time.perf_counter()-started)*1000,"qwen_gradients":audit["qwen_gradient_tensor_count"],"qwen_optimizer_params":audit["qwen_optimizer_parameter_count"]})
   if step in (20,100,200):checkpoint_checksums[f"step_{step}"]=checksum(after)
 write_csv(args.output_dir/"gradient_trajectory.csv",gradient_rows);write_csv(args.output_dir/"parameter_update_trajectory.csv",parameter_rows);write_csv(args.output_dir/"gaussian_nll_trajectory.csv",nll_rows);write_csv(args.output_dir/"loss_trajectory.csv",loss_rows);write_csv(args.output_dir/"memory_audit.csv",memory_rows)
 gradients_values=[r["raw_grad_norm"] for r in gradient_rows];overall=stats(gradients_values);early=stats(gradients_values[:20]);middle=stats(gradients_values[20:99]);late=stats(gradients_values[99:]);late_mean=100*(late["mean"]/early["mean"]-1);late_median=100*(late["median"]/early["median"]-1);nll_final=nll_rows[99:];clamp_low=float(np.mean([r["log_variance_mean"]<=-5.99 and r["log_variance_std"]<1e-4 for r in nll_final]));clamp_high=float(np.mean([r["log_variance_mean"]>=2.99 and r["log_variance_std"]<1e-4 for r in nll_final]));loss_finite=all(math.isfinite(r["total_loss"]) for r in loss_rows);stable=late_mean<20 and late_median<20 and late["fraction_gt_500"]<=early["fraction_gt_500"]+.01 and clamp_low==0 and clamp_high==0 and loss_finite;final_by_module={name:next(r for r in reversed(parameter_rows) if r["module"]==name) for name in MODULES};summary={"label":LABEL,"stage":"Phase 5A Stage C-S6 Learning-Rate-Only Trajectory Diagnostic","success":stable,"objective_restoration":restoration,"lr_contract":lr_contract,"step0_equivalence":equivalence,"raw_gradient":{"overall":overall,"steps_1_20":early,"steps_21_99":middle,"steps_100_200":late,"late_mean_change_percent":late_mean,"late_median_change_percent":late_median},"loss":{"steps_1_20":{key:loss_stats(loss_rows[:20],key) for key in ("total_loss","benefit_likelihood","harm_loss","uncertainty_regularizer")},"steps_100_200":{key:loss_stats(loss_rows[99:],key) for key in ("total_loss","benefit_likelihood","harm_loss","uncertainty_regularizer")},"all_finite":loss_finite},"gaussian_nll":{"late_fraction_collapsed_to_minus6":clamp_low,"late_fraction_saturated_to_plus3":clamp_high,"late_log_variance_mean":float(np.mean([r["log_variance_mean"] for r in nll_final])),"late_log_variance_std_mean":float(np.mean([r["log_variance_std"] for r in nll_final]))},"parameter_trajectory":{"checksums":checkpoint_checksums,"final_by_module":final_by_module,"C_S4_historical_parameter_trajectory_available":False},"cuda":{"peak_gb":max(r["cuda_peak_gb"] for r in memory_rows),"allocated_growth_last20_minus_first20_gb":float(np.mean([r["cuda_allocated_gb"] for r in memory_rows[-20:]])-np.mean([r["cuda_allocated_gb"] for r in memory_rows[:20]])),"OOM":False},"qwen_frozen":all(r["qwen_gradients"]==r["qwen_optimizer_params"]==0 for r in memory_rows),"formal_frozen3b_seed42_ready":stable,"formal_training_started":False,"test_materialized":False,"only_experimental_variable":"learning rate 3e-4 -> 3e-5","figures":plots(args,gradient_rows,parameter_rows,nll_rows,loss_rows)};write_json(args.output_dir/"summary.json",summary);print(json.dumps({"success":stable,"step0":equivalence,"gradient":summary["raw_gradient"],"gaussian":summary["gaussian_nll"],"cuda":summary["cuda"]},indent=2),flush=True)
if __name__=="__main__":main()
